# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testui3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Remember(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(536, 603)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 551, 581))
        self.graphicsView.setObjectName("graphicsView")
        self.pushButtonCheck = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonCheck.setGeometry(QtCore.QRect(370, 270, 93, 51))
        self.pushButtonCheck.setObjectName("pushButtonCheck")
        self.InputAns = QtWidgets.QLineEdit(self.centralwidget)
        self.InputAns.setGeometry(QtCore.QRect(90, 270, 231, 51))
        self.InputAns.setText("")
        self.InputAns.setObjectName("InputAns")
        self.pushButtonBack = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonBack.setGeometry(QtCore.QRect(230, 450, 93, 28))
        self.pushButtonBack.setObjectName("pushButtonBack")
        self.pushButtonNext = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonNext.setGeometry(QtCore.QRect(370, 340, 93, 51))
        self.pushButtonNext.setObjectName("pushButtonNext")
        self.LabelDisplay = QtWidgets.QLabel(self.centralwidget)
        self.LabelDisplay.setGeometry(QtCore.QRect(100, 360, 221, 31))
        self.LabelDisplay.setText("")
        self.LabelDisplay.setObjectName("LabelDisplay")
        self.ChineseWord = QtWidgets.QLabel(self.centralwidget)
        self.ChineseWord.setGeometry(QtCore.QRect(90, 70, 381, 81))
        self.ChineseWord.setObjectName("ChineseWord")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 536, 26))
        self.menubar.setObjectName("menubar")
        self.menuk = QtWidgets.QMenu(self.menubar)
        self.menuk.setObjectName("menuk")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuk.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "今日学习"))
        self.pushButtonCheck.setText(_translate("MainWindow", "确认"))
        self.pushButtonBack.setText(_translate("MainWindow", "返回主菜单"))
        self.pushButtonNext.setText(_translate("MainWindow", "下一题"))
        self.ChineseWord.setText(_translate("MainWindow", "TextLabel"))
        self.menuk.setTitle(_translate("MainWindow", "开始"))
